<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<TargetFramework>net462</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyName>OBE.XRMToolBox.BulkImageUploader</AssemblyName>
		<RootNamespace>Dataverse.BulkImageUploader</RootNamespace>

		<Version>1.0.3</Version>
		<AssemblyVersion>1.0.3</AssemblyVersion>
		<FileVersion>1.0.3</FileVersion>

		<PackageId>OBE.XRMToolBox.BulkImageUploader</PackageId>
		<Title>Bulk Image Uploader</Title>
		<Authors>SherMuhammad</Authors>
		<Description>Upload multiple images to Dataverse records</Description>
		<PackageProjectUrl>https://github.com/LionKhan/BulkImageUploader</PackageProjectUrl>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageTags>xrmtoolbox;dataverse;image;upload</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="XrmToolBoxPackage" Version="1.2023.10.67" />
		<PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.1.32" />
		<PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.52" />
		<PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
		<None Include="bin\Release\net462\OBE.XRMToolBox.BulkImageUploader.dll"
			  Pack="true"
			  PackagePath="tools\"/>
		<None Include="bin\Release\net462\OBE.XRMToolBox.BulkImageUploader.pdb"
			  Pack="true"
			  PackagePath="tools\"
			  Condition="Exists('bin\Release\net462\OBE.XRMToolBox.BulkImageUploader.pdb')"/>

		<None Include="logo.png" Pack="true" PackagePath="\"/>
		<None Include="README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>