<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>DataverseBulkImageUploader</AssemblyName>
    <RootNamespace>Dataverse.BulkImageUploader</RootNamespace>
    <Version>1.2.8.0</Version>
    <Authors>Sherkhan Lodhi</Authors>
    <Company>Dataverse Admin Tools</Company>
    <Product>Bulk Image Uploader Plugin for XrmToolBox</Product>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XrmToolBoxPackage" Version="1.2023.10.67" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.1.32" />
    <PackageReference Include="Microsoft.CrmSdk.CoreAssemblies" Version="9.0.2.52" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
  </ItemGroup>
</Project>